language: node_js

os:
  - linux
  - osx

node_js:
  - 4
  - 6
  - stable

deploy:
  provider: npm
  on:
    tags: true
  email:
    secure: LrPl3w+v9upBwU7GN8NGkeJm/htgcyKRUC7wMRAtj4wQyyqgYhN57XOE7pMghKR/RYBcZyujsAVV0xGScK6qHBw7aHWUy05Tgn8uAxW3HOqwn8samnDVNoffAsxsqdJxH+xBk3wYW7ScxOKvlmVqBfdSb22UUH5Q4ECh6ss2SM5Qro166zOAL0i4xyRDFFp6+UuIKwGLb74qCnYpvPYczYgnm7tloOooWoHm+gLF5ZsuhPchf/w0s3ssjyNaKED0vEAz6A9DRQHxI8QzSVQAVuoy0kCuQWGdRsWQYzHdRUBGGY2sbYwA6Rr13laYqzkRj0/jGVmcCODTp3b/tjchQ6sGMrQnw36FaIPl+lz7cEm4gPuzETPcJvU/dU7C7PVtzbcs5EfRABnGd664uoiJE9u0CpYk/xcq8PUlcdLkv1zbI0DKrbZWcL13Y78kx+n/NKBtltIgNswpUM0tZM8c6oqJdGyWoxbVN4sZ8gORWTqW65QCr42HDX6bs6cOXMLSOEBt0A09WW4pn1pvXNYsRHWBLCpNzlXKwDYRmANE+zAbI+4AQ3OhKN1wXqYUhkViTmYJRm5Tidb1ehjZiCmdqUVZ2BeQI8Acs/vkC27BJ4dQ6RZp69oG+usmXUuEXHMDjssr/5R9vL8nXbIaJ/ADBE36Etp+r6hwbxRPW+38EJ4=
  api_key:
    secure: THLbPCEHYB4DxqLMuYhpdFU3S28YmCOMGYaCdLYTf772cys74wTy0UBerD+MWC5NomaXPxG22fYB3uWWStz+o7o03P6yh115obyUjWmHe4h9ICcfngjbS0toW8Y4E2kJIyWHDf/v+AjqCnYdCBt6Q3ORAMz1ANti6hYuiWLwWIWH/716fJFW+zuYeemvxi2UWJP8EUFglTSUAmKFHf87RilPWh5afX54T+jbO7TP+49tsCIonwZi5zbh114u1NGG4lHLxr3iLQr3Gn6E309+YAJZRuoWbjWdJuJDt8ykRk7Y6msBwAUFAZRoFTjbvKzWc5Zflu08sTlV7CJSnZZK9RRQWy6kP9Ko6VUm5IfCGQqUToXeappTNroxXBorc4oTPnZDqulAl5Z8tlwXDO8bCh++qtsIGsTDQ0umNH/d2wGA5HtThgsTdQTMDv4uyKT8Mol8oIMhQ6G7xvsLeDmeOqvEfSpNZvGfcLmkuVcnhiLR6F5rz71NvQOm0w5qycbAGEEb7nuJ4RBL/8XW174j9zlHV2tQtcHRlxpL2ZankJbHMaQUhVAs5mT+i9ffBdRddsyyuHFM8neQFvWMdouB6fOmut1oJXPBfeleejGIU6KzsUMIWw/mLSk1T7OkLpE/HqNfXfXThIWSd85jYsLV24ZFNvlsnyzpnFA0Sk/KhPk=
  skip_cleanup: true
