language: node_js
os:
- linux
- osx
node_js:
- 4
- 6
- stable
deploy:
  provider: npm
  on:
    tags: true
  email:
    secure: nZ7rFwf6joVQo6QUNFCa2WvHZdpqkukxuwN7BbWjeubfgzhDDdiFHjJqPJ3DNRjezYgE5sBJzPFk5bpw2sZVd+BJ1tPx9KUqX0XIdmrR2g+syWTxWDiQPHtOlR7CsTWwLSrmLmGbsKVAxvn0ZmE1ECoQfA+w3RB+qK6cYaCb6pSKFBXRVY1IN8pflsvQdMvUopfZhtMpSRD21GWpzUuc8wanTvBq+nJZVoUQmumGGxMklZalAyxUKciW0n2u0DEA5F4hyZ1uJcEsH+1Dbhbszj/15V7lguGq4G6eWbKscEL5lPIK5IHBJLaZx8hnGoTOKB27IGMhDS84wEQ+xB0VmiXa+zF0hbq3oUbbopHjJCgnR+mxppvXP+hw9jsDvND1RELvcUrddSR1VqfkMI9PUTPTFmVZhD8FyAnpmGSpKPEmnqBgS5IqiLH2T/DiuNu0Pr//yRdVJK878zyACcRLAwnAdVeFeNlN/5papCKOj8amcjs2Zf0YKCDSmaEvlGEu23eOvlCGiCJpZNgP8jm6VW3PP3cxWUhgqLF2I/Y2+nGAxn4+wZM7cmpa3hfw71RSH7Tjkn05biNwTJhcUPupdgtjrV6ZtCY6JcgkW2daWb0gBtEOUykNfyy4Z52v6BXzna25L3TOnSaxtOPJJ6wAzxg0Gfh7JG2bt6b7kfUBU9k=
  api_key:
    secure: W2xcWho4UYEG/WfG9RPxwc/frI1kgqtMt96UR/BAdnom4jF5xfkNY97lhawug04xVvHbXTKPBEHF4Mj3DOj+wYT9/awB58Z4pQ3w4+hOSaH8QrOOMb+hRicEE6ildqRX9Wpe9rBFD2EUvhW7FXmUB5vntWZdEFl/ZlyVRcaARP+H3Sw4ycVx8liLUZ+NNwpgMl6w26hZqAUdCwDxzFZ2KlAZ5b0mqT1IaKY4ScRuazv38XGJGXlfCBBmdvpJEbiRPBX7fjegZ+hhEoY9TcBHToscBev419wFgh11vRx4QlcOo/HywKjItOJy+/Sw1PgXrZuiVuz0RxVaM2v2gx0PCXb8ruz1ZKPeSpg8k2DO7UVUNLEeQP2Gh9PQtl+gEzSstTHLSPjGw90S7TID/le3lmkzz9FirGjGISYXlawQxoSF/3D2dTnnQtUSglsFviEhRGSwqCf15jFutsq1Ptss0Dqu+dPXEUjwE8iQ8KY+hr1L0H7bRpYkkwutWfCXS0TL+6G+q6OksNfVFttBRaRtffBwpAs9jxQVHCOFanAz5dgOuh+c8cxSmS+ktUptWvPHMxyOwnKKYJ9KllJ2lRI1Ejuko2gGxIPBvty9jcL7XB3CsTvJ7QWAFdpVeDdB2i+eoJD2+QTbVesm9NaoKE8lICzcjkA/ExlR139p1TeawEQ=
  skip_cleanup: true
